### ISSUE TITLE
Integrating Toolbox Snippets

### ISSUE THREAD

**Issue by tklosek0** [slaier/matlab-complete#2]
Hello,

first of all, thanks for the extension!
Im wondering if there is a chance to integrate ALL snippets from specific Toolboxes into the snippets.json.
There are some snippets that are missing (rlocus() from control-toolbox, etc)
In the "funcs_spider.py" file is something going up with the modules, but i cant figure out how to use it.

Thanks in advance!

**Comment by slaier** [comment]
Thanks for your report.
The fix will be published as v1.0.4.
