### ISSUE TITLE
Layout-Issue

### ISSUE THREAD

**Issue by tklosek0** [slaier/matlab-complete#4]
Hello!
As you can see, the Information about the Method is not shown properly. I have to resize it for every information I want to read.

![image](https://user-images.githubusercontent.com/61796661/99143485-1ff71580-265e-11eb-812a-3c9ce21b1e4b.png)

Is it possible to change the layout of showing up like this in Python?

![image](https://user-images.githubusercontent.com/61796661/99143526-6fd5dc80-265e-11eb-9dbc-49162ed4123c.png)

**Comment by slaier** [comment]
The fix will be published as v1.1.1.
